# História Familiar

Vários familiares de Lowell sofreram com períodos de excitação e de depressão. A história genética de Lowell indica como esses transtornos de humor tem uma relação familiar. O tatataravô de Robert Lowell, conhecido como John “the old Judge” Lowell teve 3 filhos: John “the rebel” Lowell, Francis Cabot Lowell e Charles Lowell. John “the rebel” Lowell viveu intermitentes períodos de excesso de trabalho seguidos de meses de depressão e exaustão. Francis Cabot Lowell, tal como seu irmão, também passou por diversos períodos de “excesso de energia” seguidos de períodos de total estagnação e incapacitação. Charles Lowell, que veio a se casar com Harriet Bracket Spence, e foi o tataravô de Robert Lowell IV, também tinha certos traços de instabilidade de humor. Nos anos finais de sua vida, sua família o considerava “exageradamente excitável”.

Harriet Bracket Spence Lowell, tataravó de Robert Lowell IV, casada com Charles Lowell, também sofria de graves problemas mentais. Harriet foi internada no McLean Asylum em 19 de março de 1945 num estado que foi descrito na época como “muito irritada”. Amigos e familiares descreviam Harriet como sendo as vezes violenta e incontrolável, com mudanças de humor que variavam desde rompantes de mania até fases de desespero. Harriet passava por longos períodos nos quais ficava reclusa, períodos de insanidade e de raiva intensa. Durante sua internação passou 7 meses mais calada e isolada. Mas em novembro de 1845 seu comportamento mudou, passou a ficar mais excitada, gritando, correndo pelo hospital, dormindo pouco, e com alucinações auditivas. Harriet passou 3 anos internada, tendo voltado para casa sem grandes melhoras [@Jamison2017, pag. xiv-xvi]. Harriet faleceu em 1850, com cerca de 66 ou 67 anos [@Jamison2017, pag. 39].

Harriet Bracket Spence Lowell e Charles Lowell tiveram 6 filhos, alguns dos quais sofreram também com alguma forma de transtornos mentais: James Russell Lowell e Rebecca Lowell.

James Russell Lowell, alegou ter herdado “mais do que apenas um traço” das doenças da mãe. Relatou que em diversos momentos “tudo se tornava depressivo e o tempo deixava de existir, como se tivesse tomado o caminho da insanidade” [@Jamison2017, pag. 48]. James relatou que em algumas ocasiões pensou seriamente em tirar a própria vida. Certa vez, referindo-se a um período depressivo, escreveu que “*a gota de sangue negro que herdei de minha querida mãe se espalha sobre a pupila dos meus olhos e escurece tudo*” [^historia_familiar-1] [@Jamison2017, pag. 48].

[^historia_familiar-1]: The drop of black blood I inherited from my dear mother is apt to spread itself over the pupil of my eye and darken everything

Rebecca Lowell, irmã de James Russell, herdou uma forma mais severa da doença da mãe. Sofria períodos graves de humor deprimido, permanecendo em silêncio por semanas a fio, e períodos de violência [@Jamison2017, pag. 49].

Um dos outros filhos do casal Harriet Bracket Spence Lowell e Charles Lowell foi Robert Traill Spence Lowell I. Um nome que seria mantido por 4 gerações, até o nascimento de Robert Traill Spence Lowell IV em 1917.
